### ISSUE TITLE
Clarity on 'Hidden entity modified by a different mod or data pack' warning message

### ISSUE THREAD

**Issue by AverageCadav3r** [Tschipcraft/spawnanimations#14]
### Describe the bug

Not sure exactly what its saying, would be nice for more information, I have over 250 mods + datapacks

**Comment by Tschipcraft** [comment]
This is a warning message that only appears for players in creative, that indicates that some loot a mod/data pack tried to add to a mob may not have been applied due to Spawn Animations hiding worn armor and tools.
I will optimize this feature in the future so that it recovers automatically, but for the time being you can disable it in the settings menu (`/function spawnanimations:settings` -> Hide worn Armor and Tools) or with the command `/function spawnanimations:settings/disable_hidearmorandtools`.

**Comment by AverageCadav3r** [comment]
Ann gotcha thank you!

**Comment by AverageCadav3r** [comment]
Oh, nice was just wondering if it could specify the entity that's causing
the problem so I could deal with it
