### ISSUE TITLE
[Request] Add ability to change mob list which affected by mod

### ISSUE THREAD

**Issue by MiniRaptor** [Tschipcraft/spawnanimations#19]
### Is your feature request related to a problem? Please describe.

![2023-12-02_13 00 00](https://github.com/Tschipcraft/spawnanimations/assets/69641100/78f322dc-339e-4f54-9a7e-d07a67c82459)
Some mobs like spiders or endermans works not very well with mod, so it will be good to have ability to disable animated spawn for them

**Comment by Tschipcraft** [comment]
I am working on a solution for the eye problem as well as better animations in general for v2.0, but for now, you [can exclude them from the animation by following this tutorial in the wiki](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities).

**Comment by leftbones** [comment]
> I am working on a solution for the eye problem as well as better animations in general for v2.0, but for now, you [can exclude them from the animation by following this tutorial in the wiki](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities).

I don't suppose you ever came up with that solution, did you?

**Comment by Tschipcraft** [comment]
> I don't suppose you ever came up with that solution, did you?

This is not correct. Please see [my reply on the open issue that addresses this](https://github.com/Tschipcraft/spawnanimations/issues/25#issuecomment-1977570711). Since the mentioned approach requires a resource pack anyway, it will not be implemented until v2.0. Besides, there are more important things to implement first, like adding support for Minecraft 1.21.
