### ISSUE TITLE
Multiple problems (armor and tools not hiding)

### ISSUE THREAD

**Issue by Ferrlius** [Tschipcraft/spawnanimations#6]
## ok I have a several problems. 
- I changed activation distance and by some reason armor and tools is no longer hiding
- I play with from the fog and I think this mod causing modified entity error.
- is there a way to fix enderman, spider and creeper spawning? it doesn't make sense why this 3 mobs should have that animation at all, and on enderman and spider it looks bad
![image](https://github.com/Tschipcraft/spawnanimations/assets/87295542/34b99cd2-2f17-47e3-87a8-38cc214422f1)
![image](https://github.com/Tschipcraft/spawnanimations/assets/87295542/486d7807-3c5e-43a1-86d8-3d00d5414969)
![image](https://github.com/Tschipcraft/spawnanimations/assets/87295542/eadab07e-5796-4e58-bf7d-ba0201f071fe)

### Steps to reproduce

I don't know why armor and tools doing that, I did everything right. 
maybe it happened because I've made 92 blocks distance and then switched to 48? 
I tried to switch "hide armor and tools" off and on and it did nothing

### Expected behavior

armor and tools should be hided i guess

### Additional context

1.19.2
simulation distance 5 chunks

**Comment by Tschipcraft** [comment]
The Hide worn armor and tools setting is only checked when a new entity is hidden. So switching the setting on and off will not yield results, only new entities will follow the chosen setting. It may have happened since your Simulation Distance is pretty low compared to the previous activation distance. Please try to reset the data pack in the menu (accessible via `/trigger tschipcraft.menu`) or directly with the command `/function spawnanimations:reset` to unhide already hidden mobs. All new mobs should afterward hide their armor and tools.

I tested Spawn Animations with From the Fog v1.9, and they seem to work fine together. Do you have any other data packs or mods installed?

For your third question, please take a look at the wiki [on how to exclude entities from the animation](https://github.com/Tschipcraft/spawnanimations/wiki/Exclude-Include-Entities).

**Comment by Ferrlius** [comment]
Ok thank you, I will try to apply changes today. So simulation distance can affect it... I was actually trying to use it as a mob freezer so they wouldn't create footprints

mods that modify entities? yeah my modpack made on Fabulously Optimized, and I have Spiders 2.0. I think that problem been there before I added spider mod but I might be wrong.

**Comment by Ferrlius** [comment]
thanks, everything works fine now. so simulation distance can affect spawn animation.. I need to use it carefully then.

I also have giant spawn and spiders 2.0

**Comment by Tschipcraft** [comment]
Are you still experiencing issues with Spawn Animations?

**Comment by Tschipcraft** [comment]
I closed this issue for now.
Feel free to reopen this issue, if you're still experiencing problems.
